apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: wallysf/sorveteria-front:v2
        imagePullPolicy: Always
        env:
        - name: URL_PRODUTOS
          value: produtos-service
        - name: PORT_PRODUTOS
          value: "80"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30100

