apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-deployment
  labels:
    app: produtos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtos
  template:
    metadata:
      labels:
        app: produtos
    spec:
      containers:
      - name: produtos
        image: wallysf/sorveteria-produtos:v2
        imagePullPolicy: Always
        env:
        - name: DB_URL
          value: db-service
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: produtos-service
spec:
  selector:
    app: produtos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

